# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ebb39026287f6567e58521a5b9829f36c1da1cb3e528b31b3b938f279a5b875a0e4c6cad26e50ff49db84f048663e6081da57e6f9d6519bb1154619ebe10e5

test:
  secret_key_base: 692747d6bf414beda951ffa1d088ee04e5af8893cab86ead70ed59bef8e85c384fafc5a2644cf10bf123ab444363de1b246bd7d61bd9ee6d5f19ef68ab990a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
